- hosts: test
  remote_user: testify
  become: yes
  become_method: sudo
  connection: ssh
  vars:
    erlang_url:
    - https://packages.erlang-solutions.com/erlang-solutions-1.0-1.noarch.rpm
    erlang_key:
    - http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
    rabbitmq_url:
    - https://www.rabbitmq.com/releases/rabbitmq-server/v3.6.15/rabbitmq-server-3.6.15-1.el7.noarch.rpm 
    sensu_services:
    - rabbitmq-server
    - redis
    - sensu-server
    - sensu-api
    - uchiwa
    sensu_packages:
    - sensu
    - uchiwa
    
  tasks:
  - name: Install erlang
    yum:
      name: "{{ item }}" 
      state: present
    with_items: "{{ erlang_url }}"

  - name: import erlang key
    rpm_key:
      key: "{{ item }}"
      state: present
    with_items: "{{ erlang_key }}"

  - name: Install rabbitmq
    yum:
      name: "{{ item }}" 
      state: present
    with_items: "{{ rabbitmq_url }}"
  - name: start rabbitmq
    service: 
      name: rabbitmq-server
      state: started

  - name: rabbitmq config commands
    shell: | 
       /usr/sbin/rabbitmqctl add_vhost /sensu
       /usr/sbin/rabbitmqctl add_user sensu secret
       /usr/sbin/rabbitmqctl  set_permissions -p /sensu sensu ".*" ".*" ".*"
   
  - name: install redis
    yum:
      name: redis
      state: present
  
  - name: install sensu yum repo
    yum_repository:
      name: sensu
      description: sensu repository
      baseurl: 'https://sensu.global.ssl.fastly.net/yum/$releasever/$basearch/'
      gpgcheck: no
      enabled: yes
 
  - name: install sensu & uchiwa
    yum:
      name: "{{ item }}"
      state: present
    with_items: "{{ sensu_packages }}"

  - name: edit sensu config file
    template: 
      src: sensu.config.j2
      dest: /etc/sensu/config.json
      mode: 0644

  - name: Start sensu services & components
    service:
      name: "{{ item }}"
      state: started
    with_items: "{{ sensu_services }}"


 
